import {Footer, Header} from '@/components';
import i18nConfig from '@/i18n.config';
import type {Metadata} from 'next';
import {I18nProvider} from 'next-i18next/client';
import {getResources, getT, initServerI18next} from 'next-i18next/server';
import {Inter} from 'next/font/google';
import './globals.css';

initServerI18next(i18nConfig);

const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-inter',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{children: React.ReactNode}>) {
	const {i18n, lng} = await getT();
	const resources = getResources(i18n);

	return (
		<I18nProvider language={lng} resources={resources}>
			<html lang={lng} className={`${inter.variable} h-full antialiased`}>
				<body className="flex flex-col bg-background text-background-foreground min-h-full">
					<Header />
					<main className="grow">{children}</main>
					<Footer />
				</body>
			</html>
		</I18nProvider>
	);
}
