import {CartSidebar, Footer, Header} from '@/components';
import i18nConfig from '@/i18n.config';
import type {Metadata} from 'next';
import {I18nProvider} from 'next-i18next/client';
import {getResources, getT, initServerI18next} from 'next-i18next/server';
import {Inter} from 'next/font/google';
import './globals.css';
import {CartProvider} from '@/lib/shopify/cartContext';
import {Toaster} from 'sonner';
import {LightboxProvider} from '@/lib/lightboxContext';

initServerI18next(i18nConfig);

const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-inter',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{children: React.ReactNode}>) {
	const {i18n, lng} = await getT();
	const resources = getResources(i18n);

	return (
		<I18nProvider language={lng} resources={resources}>
			<html
				lang={lng}
				className={`${inter.variable} h-full antialiased scroll-smooth`}
			>
				<body className="flex flex-col bg-background text-background-foreground min-h-full">
					<LightboxProvider>
						<CartProvider>
							<Header />
							<main className="flex-1 flex flex-col">{children}</main>
							<CartSidebar />
							<Footer />
							<Toaster position="top-right" />
						</CartProvider>
					</LightboxProvider>
				</body>
			</html>
		</I18nProvider>
	);
}
