import {CartSidebar, Footer, Header} from '@/components/layout';
import {routing} from '@/app/i18n/routing';
import {CartProvider} from '@/lib/cart';
import {LightboxProvider} from '@/lib/lightbox';
import type {Metadata} from 'next';
import {hasLocale, NextIntlClientProvider} from 'next-intl';
import {Inter} from 'next/font/google';
import {notFound} from 'next/navigation';
import {Toaster} from 'sonner';

const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-inter',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function LocaleLayout({
	children,
	params,
}: Readonly<{children: React.ReactNode; params: Promise<{locale: string}>}>) {
	const {locale} = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	return (
		<html
			className={`${inter.variable} h-full antialiased scroll-smooth`}
			lang={locale}
		>
			<head>
				<link rel="preconnect" href="https://cdn.shopify.com" />
			</head>
			<body className="flex flex-col bg-background text-background-foreground min-h-full">
				<NextIntlClientProvider>
					<LightboxProvider>
						<CartProvider>
							<Header />
							<main className="flex-1 flex flex-col overflow-x-hidden">
								{children}
							</main>
							<CartSidebar />
							<Footer />
							<Toaster position="top-right" />
						</CartProvider>
					</LightboxProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
